### ISSUE TITLE
Review text in the box containing link to the map

### ISSUE THREAD

**Issue by DaveJephson** [publichealthengland/coronavirus-dashboard-frontend-server#55]
Change from:

**Explore the UK interactive map**
Browse cases by week.
See how the pandemic is changing across the UK.

to:

**UK interactive cases map**
View case rates across the UK

**Comment by xenatisch** [comment]
Invalid issue - wrong repository.

**Comment by DaveJephson** [comment]
This relates to the landing page text, so is in the correct repository, I think.
